package br.com.lojaoriodopeixe.vg.calc.viewer;

import br.com.lojaoriodopeixe.vg.calc.implementations.Financing;
import br.com.lojaoriodopeixe.vg.calc.utils.ParcTableModel;
import br.com.lojaoriodopeixe.vg.calc.implementations.Parcela;
import br.com.lojaoriodopeixe.vg.calc.utils.DecimalFormattedField;
import br.com.lojaoriodopeixe.vg.calc.utils.Utils;
import java.awt.Color;
import java.awt.Component;
import java.awt.Toolkit;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Objects;
import javax.swing.JOptionPane;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author vagner
 */
public class Main extends javax.swing.JFrame {

    ParcTableModel f = new ParcTableModel();
    Locale locBrazil = new Locale("pt", "BR");
    NumberFormat nfValue = NumberFormat.getInstance(locBrazil);
    NumberFormat nfInterest = NumberFormat.getInstance(locBrazil);
    NumberFormat nfIputValue = NumberFormat.getInstance(locBrazil);
    NumberFormat nfOldIputValue = NumberFormat.getInstance(locBrazil);
    Number nValue = null;
    Number nInterest = null;
    Number nInputValue = null;
    Number nOldInputValue = null;
    Financing c = new Financing();

    Double inputValue = 0d;
    Integer months = 0;
    Double interest = 0d;
    Double value = 0d;    
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        util.centerWindow(this);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/mono.png")));
        this.getContentPane().setBackground(Color.getHSBColor(0,0,10)); 
    }
    Utils util = new Utils();
    
    public int exitSystem() {
        if (javax.swing.JOptionPane.showConfirmDialog(this, "Tem certeza que deseja sair?", "Calculadora de Prestações", javax.swing.JOptionPane.YES_NO_OPTION) == 0) {
            this.dispose();
        }
        return 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TotalParcelasjTextField = new DecimalFormattedField(DecimalFormattedField.NUMERO);
        jLabel2 = new javax.swing.JLabel();
        JurosjTextField = new DecimalFormattedField(DecimalFormattedField.PORCENTAGEM);
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jNumberFormatField4 = new br.com.lojaoriodopeixe.vg.calc.utils.JNumberFormatField();
        jLabel7 = new javax.swing.JLabel();
        jNumberFormatField5 = new br.com.lojaoriodopeixe.vg.calc.utils.JNumberFormatField();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable() {
            public Component prepareRenderer(TableCellRenderer renderer,
                int rowIndex, int vColIndex) {

                Component c = super.prepareRenderer(renderer, rowIndex, vColIndex);
                if (months > 9) {
                    // altera a cor de background da linha para vermelho e foreground para branco
                    // quando o valor da coluna 3 for igual a fechado
                    if (jTable3.getValueAt(rowIndex, 0).toString().equals(months + "ª Parcela")) {
                        c.setBackground(new Color(192, 0, 0));
                        c.setForeground(Color.white);
                    } else {
                        // mantem a cor padrão de foreground
                        c.setForeground(getForeground());

                        // determina a cor de background da linha selecionada
                        if (isCellSelected(rowIndex, vColIndex)) {
                            c.setBackground(new Color(184, 207, 229));
                        } else {
                            // linhas não selecionadas, manter cor de background padrão
                            c.setBackground(getBackground());
                        }

                    }
                } else {// altera a cor de background da linha para vermelho e foreground para branco
                    // quando o valor da coluna 3 for igual a fechado
                    if (jTable3.getValueAt(rowIndex, 0).toString().equals("0" + months + "ª Parcela"

                    )) {
                        c.setBackground(new Color(192, 0, 0));
                        c.setForeground(Color.white);
                    }else {
                        // mantem a cor padrão de foreground
                        c.setForeground(getForeground());

                        // determina a cor de background da linha selecionada
                        if (isCellSelected(rowIndex, vColIndex)) {
                            c.setBackground(new Color(184, 207, 229));
                        } else {
                            // linhas não selecionadas, manter cor de background padrão
                            c.setBackground(getBackground());
                        }}}
                        return c;}}
                ;
                ValorBemjNumberFormatField = new DecimalFormattedField(DecimalFormattedField.REAL);
                ValorEntradajNumberFormatField2 = new DecimalFormattedField(DecimalFormattedField.REAL);
                ValorFinanciarNumberFormatField3 = new DecimalFormattedField(DecimalFormattedField.REAL);

                jTable2.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                    },
                    new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                    }
                ));
                jScrollPane1.setViewportView(jTable2);

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Cálculo de Prestações (Financiamento)");
                setAlwaysOnTop(true);
                setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                setResizable(false);

                jPanel1.setBackground(new java.awt.Color(153, 153, 153));

                jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText("Valor do Bem R$");

                TotalParcelasjTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                TotalParcelasjTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
                TotalParcelasjTextField.setToolTipText("");
                TotalParcelasjTextField.addFocusListener(new java.awt.event.FocusAdapter() {
                    public void focusGained(java.awt.event.FocusEvent evt) {
                        TotalParcelasjTextFieldFocusGained(evt);
                    }
                });
                TotalParcelasjTextField.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        TotalParcelasjTextFieldActionPerformed(evt);
                    }
                });
                TotalParcelasjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
                    public void keyTyped(java.awt.event.KeyEvent evt) {
                        TotalParcelasjTextFieldKeyTyped(evt);
                    }
                });

                jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                jLabel2.setText("Total de Parcelas");

                JurosjTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                JurosjTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
                JurosjTextField.setPreferredSize(new java.awt.Dimension(6, 26));
                JurosjTextField.addFocusListener(new java.awt.event.FocusAdapter() {
                    public void focusGained(java.awt.event.FocusEvent evt) {
                        JurosjTextFieldFocusGained(evt);
                    }
                });
                JurosjTextField.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        JurosjTextFieldActionPerformed(evt);
                    }
                });
                JurosjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
                    public void keyReleased(java.awt.event.KeyEvent evt) {
                        JurosjTextFieldKeyReleased(evt);
                    }
                });

                jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(255, 255, 255));
                jLabel3.setText("Juros ao Mês");

                jTextField3.setEditable(false);
                jTextField3.setBackground(new java.awt.Color(255, 255, 255));
                jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
                jTextField3.setFocusable(false);

                jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(255, 255, 255));
                jLabel4.setText("CET* a.a. %");

                jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(255, 255, 255));
                jLabel5.setText("Valor da Entrada R$");

                jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabel6.setForeground(new java.awt.Color(255, 255, 255));
                jLabel6.setText("Valor a Financiar R$");

                jButton1.setBackground(new java.awt.Color(51, 102, 255));
                jButton1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
                jButton1.setLabel("OK");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton1ActionPerformed(evt);
                    }
                });
                jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
                    public void keyPressed(java.awt.event.KeyEvent evt) {
                        jButton1KeyPressed(evt);
                    }
                    public void keyReleased(java.awt.event.KeyEvent evt) {
                        jButton1KeyReleased(evt);
                    }
                });

                jButton2.setBackground(new java.awt.Color(255, 51, 51));
                jButton2.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
                jButton2.setLabel("Sair");
                jButton2.setMaximumSize(new java.awt.Dimension(47, 23));
                jButton2.setMinimumSize(new java.awt.Dimension(47, 23));
                jButton2.setPreferredSize(new java.awt.Dimension(47, 23));
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton2ActionPerformed(evt);
                    }
                });

                jNumberFormatField4.setEditable(false);
                jNumberFormatField4.setBackground(new java.awt.Color(235, 235, 235));
                jNumberFormatField4.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
                jNumberFormatField4.setText("jNumberFormatField1");
                jNumberFormatField4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jNumberFormatField4.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jNumberFormatField4ActionPerformed(evt);
                    }
                });

                jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabel7.setForeground(new java.awt.Color(255, 255, 255));
                jLabel7.setText("Valor da Entrada Desejada R$");

                jNumberFormatField5.setEditable(false);
                jNumberFormatField5.setBackground(new java.awt.Color(235, 235, 235));
                jNumberFormatField5.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
                jNumberFormatField5.setText("jNumberFormatField1");
                jNumberFormatField5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jNumberFormatField5.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jNumberFormatField5ActionPerformed(evt);
                    }
                });

                jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabel8.setForeground(new java.awt.Color(255, 255, 255));
                jLabel8.setText("Valor da Parcela Desejada R$");

                jButton3.setBackground(new java.awt.Color(51, 153, 0));
                jButton3.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
                jButton3.setText("Cálculo Reverso");
                jButton3.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton3ActionPerformed(evt);
                    }
                });

                jTable3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                jTable3.setModel(f);
                jTable3.setGridColor(new java.awt.Color(255, 255, 255));
                jTable3.setRowHeight(23);
                jScrollPane3.setViewportView(jTable3);

                ValorBemjNumberFormatField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                ValorBemjNumberFormatField.addFocusListener(new java.awt.event.FocusAdapter() {
                    public void focusGained(java.awt.event.FocusEvent evt) {
                        ValorBemjNumberFormatFieldFocusGained(evt);
                    }
                });
                ValorBemjNumberFormatField.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        ValorBemjNumberFormatFieldActionPerformed(evt);
                    }
                });
                ValorBemjNumberFormatField.addKeyListener(new java.awt.event.KeyAdapter() {
                    public void keyPressed(java.awt.event.KeyEvent evt) {
                        ValorBemjNumberFormatFieldKeyPressed(evt);
                    }
                    public void keyReleased(java.awt.event.KeyEvent evt) {
                        ValorBemjNumberFormatFieldKeyReleased(evt);
                    }
                    public void keyTyped(java.awt.event.KeyEvent evt) {
                        ValorBemjNumberFormatFieldKeyTyped(evt);
                    }
                });

                ValorEntradajNumberFormatField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                ValorEntradajNumberFormatField2.addFocusListener(new java.awt.event.FocusAdapter() {
                    public void focusGained(java.awt.event.FocusEvent evt) {
                        ValorEntradajNumberFormatField2FocusGained(evt);
                    }
                });
                ValorEntradajNumberFormatField2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        ValorEntradajNumberFormatField2ActionPerformed(evt);
                    }
                });
                ValorEntradajNumberFormatField2.addKeyListener(new java.awt.event.KeyAdapter() {
                    public void keyReleased(java.awt.event.KeyEvent evt) {
                        ValorEntradajNumberFormatField2KeyReleased(evt);
                    }
                });

                ValorFinanciarNumberFormatField3.setEditable(false);
                ValorFinanciarNumberFormatField3.setBackground(new java.awt.Color(255, 255, 255));
                ValorFinanciarNumberFormatField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                ValorFinanciarNumberFormatField3.setFocusable(false);
                ValorFinanciarNumberFormatField3.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        ValorFinanciarNumberFormatField3ActionPerformed(evt);
                    }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(112, 112, 112)
                                                .addComponent(jLabel1))
                                            .addComponent(ValorBemjNumberFormatField))
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TotalParcelasjTextField)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addComponent(jLabel3))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(JurosjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel7)))
                                            .addComponent(jNumberFormatField4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ValorEntradajNumberFormatField2, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jNumberFormatField5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel6)
                                                        .addGap(1, 1, 1))
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)))
                                            .addComponent(ValorFinanciarNumberFormatField3))))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())
                );
                jPanel1Layout.setVerticalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TotalParcelasjTextField)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JurosjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ValorBemjNumberFormatField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ValorFinanciarNumberFormatField3)
                                    .addComponent(ValorEntradajNumberFormatField2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jNumberFormatField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jNumberFormatField5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pack();
            }// </editor-fold>//GEN-END:initComponents

    private void jNumberFormatField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNumberFormatField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNumberFormatField4ActionPerformed

    private void jNumberFormatField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNumberFormatField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNumberFormatField5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JOptionPane.showMessageDialog(this, "Função ainda não implementada. Desculpe o Transtorno!", "Oh não!", 1);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TotalParcelasjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TotalParcelasjTextFieldKeyTyped
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_TotalParcelasjTextFieldKeyTyped

    private void TotalParcelasjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalParcelasjTextFieldActionPerformed
        this.JurosjTextField.requestFocusInWindow();
    }//GEN-LAST:event_TotalParcelasjTextFieldActionPerformed

    private void JurosjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JurosjTextFieldActionPerformed
        this.jButton1.requestFocusInWindow();        
    }//GEN-LAST:event_JurosjTextFieldActionPerformed

    private void JurosjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JurosjTextFieldKeyReleased
        try {
            if (JurosjTextField.getText() != null) {
                nInterest = nfInterest.parse(JurosjTextField.getText());                
            }
        Double interest2 = nInterest.doubleValue();
      
        if (!"0,00".equals(ValorBemjNumberFormatField.getText())) {
            jTextField3.setText(String.valueOf(c.getRealCET(interest2)).replace(".", ",") + "%");            
        }
                } catch (ParseException ex) {
            System.out.println(ex.getMessage());
        }  

    }//GEN-LAST:event_JurosjTextFieldKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.exitSystem();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ValorBemjNumberFormatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorBemjNumberFormatFieldActionPerformed
            try {
            nInputValue = nfIputValue.parse(ValorBemjNumberFormatField.getText());
            nValue = nfValue.parse(ValorFinanciarNumberFormatField3.getText());
        } catch (ParseException ex) {
            //JOptionPane.showMessageDialog(this, "Valor informado não é compativel!", "Atenção!", 2);
            System.out.println(ex.getMessage());
        }
        Double bem = nInputValue.doubleValue();
        Double financiamento = nValue.doubleValue();
        Double realValue = null;
        if (!Objects.equals(bem, financiamento)) {
            realValue = bem;
        } else {
            realValue = bem;
        }
        
        ValorFinanciarNumberFormatField3.setText("");
        ValorFinanciarNumberFormatField3.setText(String.valueOf(realValue).replace(",", "."));           
        this.ValorEntradajNumberFormatField2.requestFocusInWindow();
        this.ValorEntradajNumberFormatField2.setText("");
    }//GEN-LAST:event_ValorBemjNumberFormatFieldActionPerformed

    private void ValorBemjNumberFormatFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ValorBemjNumberFormatFieldFocusGained
        ValorBemjNumberFormatField.setText("");
        ValorBemjNumberFormatField.selectAll();
    }//GEN-LAST:event_ValorBemjNumberFormatFieldFocusGained

    private void ValorBemjNumberFormatFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ValorBemjNumberFormatFieldKeyReleased
       
    }//GEN-LAST:event_ValorBemjNumberFormatFieldKeyReleased

    private void ValorEntradajNumberFormatField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorEntradajNumberFormatField2ActionPerformed
    Double realValue = 0d;   
        try {
            nInputValue = nfIputValue.parse(ValorEntradajNumberFormatField2.getText());
            nValue = nfValue.parse(ValorBemjNumberFormatField.getText());
            //nOldInputValue = nfOldIputValue.parse(ValorFinanciarNumberFormatField3.getText());
        } catch (ParseException ex) {
            //JOptionPane.showMessageDialog(this, "Valor informado não é compativel!", "Atenção!", 2);
            System.out.println("Aqui?" + ex.getMessage());
        }        
        Double entrada = nInputValue.doubleValue();
        Double financiamento = nValue.doubleValue();
//        if (entrada > financiamento) {
//            JOptionPane.showMessageDialog(this, "Valor da entrada é maior ou igual ao Financiamento!", "Atenção!", 2);
//            Double aux = nOldInputValue.doubleValue();
//            ValorFinanciarNumberFormatField3.setText("");
//            ValorEntradajNumberFormatField2.setText("");
//            ValorBemjNumberFormatField.setText("");
//            entrada = 0d;
//            financiamento = 0d;
//            
//        }
        financiamento = nValue.doubleValue();
        if (entrada > 0) {
        realValue = financiamento - entrada;        
        ValorFinanciarNumberFormatField3.setText(String.valueOf(realValue));
        }        
        this.TotalParcelasjTextField.requestFocusInWindow();
    }//GEN-LAST:event_ValorEntradajNumberFormatField2ActionPerformed

    private void ValorEntradajNumberFormatField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ValorEntradajNumberFormatField2KeyReleased

    }//GEN-LAST:event_ValorEntradajNumberFormatField2KeyReleased

    private void ValorBemjNumberFormatFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ValorBemjNumberFormatFieldKeyPressed
        
    }//GEN-LAST:event_ValorBemjNumberFormatFieldKeyPressed

    private void ValorBemjNumberFormatFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ValorBemjNumberFormatFieldKeyTyped
        
    }//GEN-LAST:event_ValorBemjNumberFormatFieldKeyTyped

    private void ValorEntradajNumberFormatField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ValorEntradajNumberFormatField2FocusGained
      
    }//GEN-LAST:event_ValorEntradajNumberFormatField2FocusGained

    private void ValorFinanciarNumberFormatField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorFinanciarNumberFormatField3ActionPerformed
        this.jButton1.requestFocusInWindow();
    }//GEN-LAST:event_ValorFinanciarNumberFormatField3ActionPerformed

    private void TotalParcelasjTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TotalParcelasjTextFieldFocusGained
        this.TotalParcelasjTextField.setText("");
        this.TotalParcelasjTextField.selectAll();
    }//GEN-LAST:event_TotalParcelasjTextFieldFocusGained

    private void JurosjTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JurosjTextFieldFocusGained
        DecimalFormattedField d = new DecimalFormattedField(DecimalFormattedField.PORCENTAGEM);
        JurosjTextField.setText("");
        JurosjTextField.selectAll();
    }//GEN-LAST:event_JurosjTextFieldFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            nValue = nfValue.parse(ValorFinanciarNumberFormatField3.getText());
            nInterest = nfInterest.parse(JurosjTextField.getText());
            nInputValue = nfIputValue.parse(ValorEntradajNumberFormatField2.getText());

            value = nValue.doubleValue();
            interest = nInterest.doubleValue();
            months = Integer.parseInt(TotalParcelasjTextField.getText());
            inputValue = nInputValue.doubleValue();

            List<Parcela> parcelas = new ArrayList<>();

            //System.out.println("Resultado: " + c.getInstalment(value, interest, months, 0d));

            for (int i = 0; i < months * 2; ++i) {
                Parcela parcela = new Parcela();
                if (i > 1) {
                    DecimalFormat decFormat = new DecimalFormat("¤ #,###,##0.00");
                    if (i < 10) {
                        parcela.setNumero("0" + i + "ª Parcela");
                    } else {
                        parcela.setNumero(i + "ª Parcela");
                    }
                    parcela.setParcela(String.valueOf(decFormat.format(c.getInstalment(value, interest, i, 0d))));
                    parcela.setTotalParcelado(String.valueOf(decFormat.format(c.getInstalment(value, interest, i, 0d).multiply(new BigDecimal(i)).add(new BigDecimal(inputValue)))));
                    parcela.setTotalGeral(String.valueOf(decFormat.format(c.getInstalment(value, interest, i, 0d).multiply(new BigDecimal(i)).add(new BigDecimal(0d)))));
                    parcelas.add(parcela);
                }
            }
            f.limpar();
            f.addListaDeParcelas(parcelas);
            this.ValorBemjNumberFormatField.setText("");
            this.ValorEntradajNumberFormatField2.setText("");
            this.TotalParcelasjTextField.setText("");
            this.JurosjTextField.setText("");
            this.ValorBemjNumberFormatField.requestFocusInWindow();
        } catch (ParseException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Um ou mais valores não informados ou incompatíveis!", "Atenção!", 2);
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyReleased

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        try {
            nValue = nfValue.parse(ValorFinanciarNumberFormatField3.getText());
            nInterest = nfInterest.parse(JurosjTextField.getText());
            nInputValue = nfIputValue.parse(ValorEntradajNumberFormatField2.getText());

            value = nValue.doubleValue();
            interest = nInterest.doubleValue();
            months = Integer.parseInt(TotalParcelasjTextField.getText());
            inputValue = nInputValue.doubleValue();

            List<Parcela> parcelas = new ArrayList<>();

            //System.out.println("Resultado: " + c.getInstalment(value, interest, months, 0d));

            for (int i = 0; i < months * 2; ++i) {
                Parcela parcela = new Parcela();
                if (i > 1) {
                    DecimalFormat decFormat = new DecimalFormat("¤ #,###,##0.00");
                    if (i < 10) {
                        parcela.setNumero("0" + i + "ª Parcela");
                    } else {
                        parcela.setNumero(i + "ª Parcela");
                    }
                    parcela.setParcela(String.valueOf(decFormat.format(c.getInstalment(value, interest, i, 0d))));
                    parcela.setTotalParcelado(String.valueOf(decFormat.format(c.getInstalment(value, interest, i, 0d).multiply(new BigDecimal(i)).add(new BigDecimal(inputValue)))));
                    parcela.setTotalGeral(String.valueOf(decFormat.format(c.getInstalment(value, interest, i, 0d).multiply(new BigDecimal(i)).add(new BigDecimal(0d)))));
                    parcelas.add(parcela);
                }
            }
            f.limpar();
            f.addListaDeParcelas(parcelas);
            this.ValorBemjNumberFormatField.setText("");
            this.ValorEntradajNumberFormatField2.setText("");
            this.TotalParcelasjTextField.setText("");
            this.JurosjTextField.setText("");
            this.ValorBemjNumberFormatField.requestFocusInWindow();
        } catch (ParseException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Um ou mais valores não informados ou incompatíveis!", "Atenção!", 2);
            System.out.println("Aqui?" + ex.getMessage());
        }
    }//GEN-LAST:event_jButton1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Main().setVisible(true);
            }
        });
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JurosjTextField;
    private javax.swing.JTextField TotalParcelasjTextField;
    private javax.swing.JTextField ValorBemjNumberFormatField;
    private javax.swing.JTextField ValorEntradajNumberFormatField2;
    private javax.swing.JTextField ValorFinanciarNumberFormatField3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private br.com.lojaoriodopeixe.vg.calc.utils.JNumberFormatField jNumberFormatField4;
    private br.com.lojaoriodopeixe.vg.calc.utils.JNumberFormatField jNumberFormatField5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
